### ISSUE TITLE
Trying to upload saved file. Returning status: 0. 

### ISSUE THREAD

**Issue by swennemans** [kamilkp/react-native-file-transfer#1]
#### EDIT: on further exploration it seems that the request isn't made at all. Please ignore my previous post/title.

The `res` object is logging `status: 0` . From your readme this would mean that the protocol is not supported. I have save my image to disk using react-native-camera. An example: https://github.com/rt2zz/reactNativeCameraDemo/blob/master/index.ios.js

I would expect this to work, but it isn't working. How then would I set this up?
What i've tried:

`var path = 'this.state.image.uri;`
`var path = 'file:/' + this.state.image.uri;`
`var path = 'file:/' + this.state.image.uri + '.jpeg';`
`var path = 'file:/' + this.state.image.uri + '.jpg';`

this would result in `file://filepath` example: `file://var/mobile/Containers/Data/Application/7175E01F-543E-4943-8BF4-BE602EC71D34/Documents/B51BA6A8-9F08-469F-86F4-BFC4C1878A30"`

And then example of code:

``` javascript
var file = {
            path,
            uploadURL,
            fileName,
            mimeType,
            data: {
            }
        };

        NativeModules.FileTransfer.upload(file, res => {
            if (file) {
                console.log('FILE:', file)
                console.log('RES', res); //return {"status": 0, "data" : ""}
            } else {
                console.log('res', res)
            }
        });
```

BTW: I think your `readme.md` has an error. shouldn't it be `NativeModules` instead of `NativeMethods`? If you want I can do a pull request. :smile:

**Comment by kamilkp** [comment]
Pull on the readme? Sure, its an obvious typo :)
You write "uploadURL" but should write "uploadUrl". Chceck that for starters. Also make sure you have the lastest version of the lib. I added support for file:// protocol recently.

**Comment by swennemans** [comment]
The problem was with the version of the lib. It's working now :+1:  Thanks for sharing. 

btw > i did a pull request for the type in the `readme.md` and added small info in where to to place the `RTCFileTransfer.m`.

**Comment by wookiem** [comment]
@swennemans I believe I am trying to solve the same file upload as you've already solved.  I am trying to upload a file from react-native-camera with a capture target Camera.constants.CaptureTarget.disk.  I am trying to upload this file to Parse.  

The response I'm getting is: Object {status: 0, data: ""}

Did you encounter this error and if so any suggestions on how to proceed?  
Thanks!

```
uploadPhotoToParse(sessionToken ) {

photoURL = '/Users/wookiem/Library/Developer/CoreSimulator/Devices/480BDB0E-783A-4A6E-913C-504D4BA7E8C7/data/Containers/Data/Application/83D47391-AD6D-4DED-86B7-B784A7D1B7D6/Documents/DFC5EC3D-4021-464D-82CB-06990A86D5A0.jpg';

fileName = 'proposalPhoto.jpg';

var uploadUrl = 'https://api.parse.com/1/files/'
var mimeType = 'image/jpeg';

var headers = {
    'X-Parse-Application-Id': CONFIG.PARSE.APP_ID,
    'X-Parse-REST-API-Key': CONFIG.PARSE.REST_API_KEY
  } 

var obj = {
        uri: 'file:/' + photoURL, 
        fileName: fileName,
        mimeType: mimeType,
        headers: headers,
        data: {
        }
};

NativeModules.FileTransfer.upload(obj, (err, res) => {
        console.log(err);
        console.log(res);
});
}`
```
