### ISSUE TITLE
Library/React/Base does not exist

### ISSUE THREAD

**Issue by JakeRuth** [kamilkp/react-native-file-transfer#14]
Apologies if this is super noobie, but your README is not clear to me.

I am trying very hard to add this to my project and I cannot find the folder you specified and it doesn't seem right to me to just create it, since I normally don't have to do that to use a npm module.

Can you update the readme?  I am a software engineer I am just not familiar with Obj-C at all and my only app coding experience with react-native in javascript.

Thanks!

**Comment by austin1030** [comment]
from xcode, left panel...there are 2 ways to do..
1. click on your project name (and expend list)
2. right click on "Libraries" and select "Add file to "<your project name>"..."
3. keep default selections and select node_modules -> react-native-file-transfer -> RCTFileTransfer.m
4. click "Add" bottom of the window

OR
1. click on your project name
2. (look at top on center panel) and click "Build Phases"
3. click "Compile Sources" and click +
4. click "Add other" button bottom left corner of window
5. select node_modules -> react-native-file-transfer -> RCTFileTransfer.m

Hope I'm not missing anything.

Good luck

**Comment by JakeRuth** [comment]
I was able to get this working by adding the file to my [Profile-Name] folder.

I would be nice for the README to be more clear, I may make a pull request later if I have time (time is very hard to come by nowadays).

Thanks for your response @austin1030 !
