### ISSUE TITLE
Return error first callback

### ISSUE THREAD

**Issue by rt2zz** [kamilkp/react-native-file-transfer#4]
Would you be open to having callback be error first i.e. `callback(err, response)`

This will make it more like superagent/request api's, making it easier to parse the response and plug it into existing code.

**Comment by jtremback** [comment]
:+1: I think it's really important to keep a consistent callback API across libraries. Callbacks are an async abstraction, and there are a lot of libraries that expect them to act a certain way.

**Comment by kamilkp** [comment]
I can do that. If only the `RCT_EXPORT_METHOD` macro supports passing two arguments in the callback. I'll check that.

**Comment by jtremback** [comment]
Thanks for the great module!

**Comment by rt2zz** [comment]
@kamilkp I implemented it in #5 - granted it is bundled with a few other changes you may or may not like. I you want I can split the callpack portion into a seperate PR

**Comment by kamilkp** [comment]
Please do. I will merge it right away.

**Comment by kamilkp** [comment]
It has been fixed in the latest marged PR
